### PR TITLE
Creating a new site using Bootstrap 4

### PR DESCRIPTION
**Pull request by jairjaramillo**

### CODE REVIEW

**Review by Ispirett — CHANGES_REQUESTED** [review]
Hey, great job @jairjy  with this project so far there are just some thing's to attend too.
image

There are just a few things to it adjust.

**This section should look more  like the original site**
There is a lot of extra room on the sides.
current

This section should also look like the original at around 1050 and under. The images are getting to thin
current2

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Good job :+1: 
Your clone looks quite good but we need to fix a few things before we can merge.
Screenshot from 2019-10-03 19-11-26
- [ ] Remove the vertical scroll bar in the top story section

Screenshot from 2019-10-03 19-11-34
- [ ] make your subscribe section look like the one for the [original](https://www.newsweek.com/) site
- [ ] make your README more professional. Learn how to from [here](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2)

### Make those changes and re-submit

**Review by Redvanisation — CHANGES_REQUESTED** [review]
### Hello @jairjy   🌟

**Great work on this project, but we need to fix the issues below before moving on ⬇️** 

1. Make the README file more descriptive, check [this](https://github.com/othneildrew/Best-README-Template) link for reference.

2. **[For future projects] -** Please make your branch names and commit messages more descriptive, and add a short summary with the changes made to the future pull requests.

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

**Comment by jairjaramillo** [comment]
Sorry but I don’t see how I can make my README file more descriptive without resorting to adding filler or redundancy.

I already have a description about it, and links to Microverse, the github.io link to my finished page, the original assignment from The Odin Project, and the original page for reference. Also my name and social accounts.

Having such information linked into my README, the only description I used is "This project requests students to build a replica of the news site Newsweek.com using the Bootstrap framework” which is pretty much what my project is and tries to be.

My project doesn’t have prerequisites, installation instructions, usage, roadmap, contributors or acknowledgements. Thus I see unnecessary to add a table of contents.

Thanks for your time.

Jair.

**Review by uche-inyama — APPROVED** [review]
## Hi jairjy, 

         This project is approved, go ahead and merge with master branch.

[**Observation**] Use markdown syntax, to wrap the links you referenced neatly, in the comment you made.

**Pull request merged**
